/*
 * DjhItemIteminfoMapper.java
 * Copyright(C) 2014-2016 宁波大家好科技有限公司深圳分公司
 * All rights reserved.
 * -------------------------------------------------------
 * 15-8-28 下午4:45 Created.
 * author:苏阳华
 */
package com.user.mapper;

import com.user.model.DjhItemIteminfo;

public interface DjhItemIteminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table djh_item_iteminfo
     *
     * @mbggenerated Fri Aug 28 16:45:12 CST 2015
     */
    int deleteByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table djh_item_iteminfo
     *
     * @mbggenerated Fri Aug 28 16:45:12 CST 2015
     */
    int insert(DjhItemIteminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table djh_item_iteminfo
     *
     * @mbggenerated Fri Aug 28 16:45:12 CST 2015
     */
    int insertSelective(DjhItemIteminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table djh_item_iteminfo
     *
     * @mbggenerated Fri Aug 28 16:45:12 CST 2015
     */
    DjhItemIteminfo selectByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table djh_item_iteminfo
     *
     * @mbggenerated Fri Aug 28 16:45:12 CST 2015
     */
    int updateByPrimaryKeySelective(DjhItemIteminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table djh_item_iteminfo
     *
     * @mbggenerated Fri Aug 28 16:45:12 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DjhItemIteminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table djh_item_iteminfo
     *
     * @mbggenerated Fri Aug 28 16:45:12 CST 2015
     */
    int updateByPrimaryKey(DjhItemIteminfo record);
}